dubbo:
  application:
    qosEnable: false
  protocol:
    port: 17778
  registry:
    address: zookeeper://127.0.0.1:2181
ktf:
  cache:
    enabled: true
  zkconfig:
    connect-str: 127.0.0.1:2181
server:
  port: 7778
  servlet:
    context-path: /${spring.application.name}
spring:
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 30
        max-idle: 30
        max-wait: 60000
        min-idle: 5
    port: 7000
    timeout: 5000
