spring:
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 30
        max-idle: 30
        max-wait: 60000
        min-idle: 5
    port: 7000
    timeout: 5000
    
dubbo:
  application:
    qosEnable: false
  protocol:
    port: -1
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  

