server:
  undertow:
        # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程不要设置过大，
        # 如果过大，启动项目会报错：打开文件数过多
    io-threads: 4
        # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
        # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 32
        # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
        # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
        # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
      
spring:
  application:
    name: runner-mp
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: '@profileActive@'
  main:
    allow-bean-definition-overriding: true
  mvc: 
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
    
mybatis-plus:
  mapper-locations: [classpath*:com/kivi/dashboard/*/mapper/xml/*Mapper.xml]
  type-aliases-package: com.kivi.dashboard.*.entity
  global-config:
    db-config:
      id-type: ID_WORKER
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  level:
    com.kivi: trace
    com.baomidou: trace
    java.rmi: info
    
ktf:
  cache:
    enabled: true
    redis:
      client-type: lettuce
  common:
    component-scan: com.kivi
  db:
    mappers: com.kivi.dashboard
  dashboard: 
    auth: none
  swagger:
    enabled: true
    title: KMS管理后台API接口
    version: 1.0.0

