spring:
  application:
    name: dubbo-server
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    active: '@profileActive@'

dubbo:
  application:
    name: dubbo-server
  protocol:
    name: dubbo
    optimizer: com.kivi.dubbo.serialize.SerializationOptimizerImpl
    serialization: kryo
    status: server
  provider:
    retries: 0
  #registry:
  #  client: nacos
  scan.base-packages: com.kivi.demo
ktf:
  common:
    component-scan: com.kivi
  db:
    mappers: com.kivi.**.mapper

knife4j:
  enable: true
  openapi:
    title: Demo Dubbo provider文档
    description: "**Dubbo**服务端demo的文档"
    email: test@foxmail.com
    concat: inssec
    url: https://www.inssec.cn
    version: v1.0
    license: Apache 2.0
    license-url: https://www.inssec.cn/
    terms-of-service-url: https://www.inssec.cn/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.kivi.demo.controller