spring:
  application:
    name: dubbo-server
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
  profiles:
    active: '@profileActive@'

dubbo:
  application:
    name: dubbo-server
  protocol:
    id: dubbo
    name: dubbo
    optimizer: com.kivi.dubbo.serialize.SerializationOptimizerImpl
    serialization: kryo
    status: server
  provider:
    threadpool: eager
    loadbalance: shortestresponse
    retries: 0
  #registry:
  #  client: nacos
  scan:
    base-packages: com.kivi.demo.service

ktf:
  common:
    component-scan: com.kivi
  cache:
    enabled: true
    redis:
      client-type: lettuce
  db:
    mappers: com.kivi.**.mapper
